### PR TITLE
Improve importing defaults and destructured from the same modules

### LINKED ISSUE #83: Importing default and destructuring unnecessarily creates two separate imports when using import declaration keyword
Currently, with `aliases` configuration like the following:

```json
"React": {
  "path": "react",
  "destructure": [
    "PropTypes"
  ]
}
```

importing both `React` and `PropTypes` will result in:

```js
import React from 'react';
import { PropTypes } from 'react';
```

but it would be better if it instead resulted in:

```js
import React, { PropTypes } from 'react';
```

I'm not sure if there is any equivalent syntax for CommonJS imports, but it would be really nice if ImportJS did this when using the `import` declaration keyword. I suppose if you were using CommonJS, it would be better to have one `require` and one assignment after the fact than two `require`s:

```js
const React = require('react');
const { PropTypes } = React;
```

### PR DESCRIPTION
**Pull request by lencioni**
Fixes #83.

### CODE REVIEW

**Comment by lencioni** [comment]
I still haven't resolved the issue yet. I think that by using `require` instead of the variable when destructuring, it helps by not creating a separate block the second time, but the sort order changes. I think that once I get the sorting to happen correctly the first time we'll be good to go. Stand by.

**Comment by lencioni** [comment]
Alright, I think this is good to go now.

**Comment by trotzig** [comment]
Agreed. I'll merge when Travis gives her +1.

**Comment by lencioni** [comment]
Travis is green!

**Comment by trotzig** [comment]
wow, you're faster than Travis yourself...

**Pull request merged**
