### PR TITLE
Use FindError instead of ParseError when failing find

### PR DESCRIPTION
**Pull request by lencioni**
As @trotzig pointed out, ParseError isn't ideal here. So I decided to
replace it with a FindError and add a test to verify that it works.

### CODE REVIEW

**Comment by trotzig** [comment]
Looks like you added some other stuff in the commit too.

**Comment by lencioni** [comment]
What other stuff?

It looks like my new spec failed in travis, but it passes locally. Not really sure why yet, but I would guess that `find` behaves differently there than it is on my laptop.

**Comment by lencioni** [comment]
I added a check to fail if lookup path is an empty string, so specs should pass now.

**Comment by trotzig** [comment]
I was confused. Looks good!

**Pull request merged**
