### PR TITLE
Move max line length

### PR DESCRIPTION
**Pull request by trotzig**

### CODE REVIEW

**Comment by lencioni** [comment]
:+1:

**Comment by lencioni** [comment]
Geez, Travis is slow today. @trotzig did you run specs locally?

**Comment by trotzig** [comment]
Yes, I did. They pass on 2.2.3 at least.

**Comment by lencioni** [comment]
Good enough for me. I'm merging it!

**Comment by trotzig** [comment]
Yihaa! :cow: :boy:

**Pull request merged**
