### PR TITLE
Improve Travis build matrix

### PR DESCRIPTION
**Pull request by lencioni**

### CODE REVIEW

**Comment by lencioni** [comment]
Looks like this won't pass until https://github.com/travis-ci/travis-ci/issues/5361 is resolved. In the meantime we could use 2.3.0 instead of 2.3, but I think we may as well just wait.

**Comment by trotzig** [comment]
Sounds good. This isn't likely to rot much even if we have to keep it around. Will you keep an eye out for resolutions to that travis-ci issue?

**Comment by lencioni** [comment]
Sure!

**Comment by lencioni** [comment]
I think this has actually rotted and I'm tired of looking at it, so I'm just going to close this for now. I plan to push a new one once it is working.

**Pull request closed without merging**
