### PR TITLE
Destructured wrapping

### PR DESCRIPTION
**Pull request by lencioni**

### CODE REVIEW

**Comment by lencioni** [comment]
Ah bummer. This fails on Ruby 1.9.3 because I am using keyword arguments. What would you prefer: I replace keyword args with regular args or I remove 1.9.3 from the build matrix?

**Comment by trotzig** [comment]
Well, since I added `slop` a while back, I think we can't use 1.9.3 anyway. At least based on the error message reported at the top of https://github.com/trotzig/import-js/issues/96

You have my blessing.

**Comment by trotzig** [comment]
let me know when you are done

**Comment by lencioni** [comment]
@trotzig done!

**Comment by trotzig** [comment]
I made you a collaborator, so feel free to merge at will!

**Comment by lencioni** [comment]
Sweet, thanks!

**Pull request merged**
